### ISSUE TITLE
Rock score calculator cannot tolerate deeply un-rock programs (division by 0 error)

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-bon-jova-rockstar#137]
If I have this program 

```
say hi
```

I get this stack trace:

```
Caused by: java.lang.ArithmeticException: / by zero
	at io.quarkiverse.bonjova.lyrics.LyricsRatingCalculator.calculateLyricsRating(LyricsRatingCalculator.java:38)
	at io.quarkiverse.bonjova.deployment.rockscore.RockScoreCalculator.calculateRockScore(RockScoreCalculator.java:18)
	at io.quarkiverse.bonjova.deployment.BonJovaQuarkusExtensionProcessor.lambda$generateRockFiles$4(BonJovaQuarkusExtensionProcessor.java:145)
```

**Comment by hannotify** [comment]
Good point. Solved it. :-)
