### ISSUE TITLE
Can we cache the lyrics in the extension so apps can be run offline?

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-bon-jova-rockstar#80]
I notice if I run the quarkus app offline, I get the following failures:

```
Caused by: java.util.concurrent.ExecutionException: java.net.UnknownHostException: api.lyrics.ovh
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.example.bon.jova.quarkus.extension.deployment.lyrics.RemoteLyricsReader.lambda$readRemoteLyrics$2(RemoteLyricsReader.java:149)
        ... 24 more
Caused by: java.net.UnknownHostException: api.lyrics.ovh
        at java.base/java.net.InetAddress$CachedLookup.get(InetAddress.java:988)
```

If we baked the lyrics into the extension, the app could run without needing network access. That might make demos more robust.

Obviously, this is only a nice-to-have, and not critical.

**Comment by hannotify** [comment]
That is a good point - I could probably make it work by changing the `target/lyrics` destination to `src/main/resources/lyrics` and putting that location in the `.gitignore`. Then already downloaded lyrics could survive an `mvn clean`.

**Comment by holly-cummins** [comment]
I think there's two potential solutions: 
- Extension user has 'responsibility' for downloading lyrics, but they're cached so they survive a clean 
- The extension author has responsibility for downloading the lyrics, and they're packaged into the extension binary. 

I had in mind the second, but making a jar full of song lyrics and putting it on maven central might not be ideal in terms of copyright, in the same way that putting them in our repo wasn't. :)

**Comment by hannotify** [comment]
Solution #3: expose the lyrics frequencies in the extension.
